[tool.poetry]
name = "dependabot-poc"
version = "0.1.0"
description = "POC for Dependabot"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.28.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
